name: CI

on:
  push:
    branches: [ "main" ]
    paths: ['data.yaml']
  pull_request:
    branches: [ "main" ]
    paths: ['data.yaml']

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GitHub Copilot CLI
        run: curl -fsSL https://gh.io/copilot-install | bash

      - name: Update readme.md
        run: copilot -p "update readme.md according on data in data.yaml" --allow-all-tools
